### ISSUE TITLE
Allow installation via Composer

### ISSUE THREAD

**Issue by erikhansen** [GetFinancing/getfinancing-magento2#2]
I would recommend refactoring your module so that it can be installed via Composer OR via the manual install method you use now. You can reference this repo structure and readme for details on how you could change things to support both install methods: 

https://github.com/turnto/magento2-turnto-socialcommerce

**Comment by sindreu** [comment]
Thanks for the comment. We will take it into account for future releases.

**Comment by sindreu** [comment]
We have made the module available through composer. 

Can you give it a try and see if it works for you?

**Comment by erikhansen** [comment]
@sindreu I'd be happy to test the Composer install, but due to our internal coding standards, I can't install this extension until the issues I mentioned in https://github.com/GetFinancing/getfinancing-magento2/issues/1 are addressed.
