### ISSUE TITLE
LoggerInterface should not be included as a dependency where Context is already a dependency

### ISSUE THREAD

**Issue by ntoombs19** [GetFinancing/getfinancing-magento2#3]
This is a very critical issue that any customer using the typical deployment process will experience. I am very surprised you did not encounter this in your testing. I would like to use your module for a client but this issue is preventing me from moving forward.

This module includes the class `\Psr\Log\LoggerInterface` as a dependency in the `__constructor()` method of `\Getfinancing\Getfinancing\Block\Notification` while also including the class `\Magento\Framework\View\Element\Template\Context` as a dependency. Magento 2 does not allow you to compile classes that include a dependency that is already included as a dependency of another dependency. Since the `Context` class already includes `\Psr\Log\LoggerInterface` as a dependency, running `bin/magento setup:di:compile` will result in this error:

```bash
Errors during compilation:
Getfinancing\Getfinancing\Block\Notification
Incorrect dependency in class Getfinancing\Getfinancing\Block\Notification
\Psr\Log\LoggerInterface already exists in context object
```

This can be fixed by removing the `\Psr\Log\LoggerInterface` dependency entirely and setting the `_logger` property in the `__constructor()` method to the following:

```php
// $this->_logger = $logger; This should be changed to the line below
$this->_logger = $context->getLogger();
```

**Comment by sindreu** [comment]
Thanks for the report. We were aware of the error, but seems non-critical as the module installs correctly. 

Please proceed with the installation and will provide an update to this module when time allows. 

Thank you

**Comment by ntoombs19** [comment]
This is a critical error for us and I will not proceed without this error being fixed. I've provided you with the changes needed to fix this. If necessary I can submit a PR.

**Comment by sindreu** [comment]
Please submit the PR so it can be fixed asap.

Thanks again Nathan.
