### ISSUE TITLE
Lightbox doesn't appear when selecting Get Financing payment method

### ISSUE THREAD

**Issue by ntoombs19** [GetFinancing/getfinancing-magento2#9]
Nothing happens when selecting the Get Financing Payment method. The README file says a lightbox should appear but it never does. Also, I noticed that the notification.phtml template does not exist even though the block declaring it does exist. Also the Block and Controller classes exist. I suspect that the notification.phtml file was removed for some reason or perhaps it was never added. Either way, this module does not appear to be working as expected.

**Comment by sindreu** [comment]
Hi Nathan

What merchant are you trying to install GetFinancing? Can you reach us at integrations@getfinancing.com? 

The module works but you seem to have wrong credentials...

**Comment by sindreu** [comment]
hi, 

we have finished our improvement work on our magento2 plugin.

We recommend you to install the latest version from our github. It should work fine with magento2.1

Thanks.
